spring.application.name=ratelimiting

spring.config.import=aws-parameterstore:/config/ratelimiting/

spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.parameterstore.endpoint=http://localhost:4566
spring.cloud.aws.parameterstore.region=us-east-1
